[package]
name = "qtrc-extract"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
binrw = "0.8"
clap = { version = "3", features = ["derive"] }
goblin = "0.5"
flate2 = "1"
rangemap = "1"
